import { platformApi } from "@/lib/api/base-api";
import type { ApiResponse, PaginatedResult } from "@/lib/api/types";
import { unwrapApiResponse } from "@/lib/api/types";

export const paymentMilestoneStatuses = ["Not Due", "Due", "Partially Paid", "Paid", "Overdue", "Waived", "Cancelled"] as const;
export const paymentMethods = ["Bank Transfer", "Cash", "Cheque", "PayPal", "Stripe", "Card", "Lynk", "Other"] as const;
export type PaymentMilestoneStatus = (typeof paymentMilestoneStatuses)[number];
export type PaymentMethod = (typeof paymentMethods)[number];

export type PaymentMilestone = { id: string; client_project_id?: string | null; title?: string | null; description?: string | null; amount?: number | null; currency?: string | null; due_date?: string | null; status?: string | null; sort_order?: number | null; paid_amount?: number | null; outstanding_amount?: number | null; project?: { id?: string; title?: string | null; total_value?: number | null; payment_status?: string | null } | null; client?: { id?: string; business_name?: string | null; status?: string | null } | null; created_at?: string | null; updated_at?: string | null };
export type PaymentRecord = { id: string; client_project_id?: string | null; payment_milestone_id?: string | null; amount_paid?: number | null; payment_date?: string | null; payment_method?: string | null; reference_number?: string | null; notes?: string | null; receipt_url?: string | null; recorded_by?: string | null; is_external_payment?: boolean | null; status?: string | null; created_at?: string | null; updated_at?: string | null };
export type PaymentsSummary = { total_outstanding?: number; total_paid?: number; overdue_amount?: number; due_this_week?: number; due_this_month?: number; payments_received_this_month?: number; overdue_milestones_count?: number; projects_with_overdue_payments?: number; projects_count?: number };
export type PaymentMilestoneInput = { title: string; description?: string; amount: number; due_date?: string; status?: PaymentMilestoneStatus; sort_order?: number };
export type PaymentRecordInput = { payment_milestone_id?: string; amount_paid: number; payment_date: string; payment_method: PaymentMethod; reference_number?: string; notes?: string; receipt_url?: string; is_external_payment?: boolean };
export type ListPaymentMilestonesQuery = { page?: number; limit?: number; search?: string; client_project_id?: string; status?: string; overdue?: "true" | "false"; sort_by?: string; sort_order?: "asc" | "desc" };
export type ListPaymentRecordsQuery = { page?: number; limit?: number; search?: string; client_project_id?: string; payment_milestone_id?: string; payment_method?: string; sort_by?: string; sort_order?: "asc" | "desc" };

export const paymentsApi = platformApi.injectEndpoints({ endpoints: (builder) => ({
  getPaymentsSummary: builder.query<PaymentsSummary, void>({ query: () => "/admin/payments/summary", transformResponse: (response: ApiResponse<PaymentsSummary>) => unwrapApiResponse(response), providesTags: ["Payments"] }),
  listPaymentMilestones: builder.query<PaginatedResult<PaymentMilestone>, ListPaymentMilestonesQuery | void>({ query: (params) => ({ url: "/admin/payments/milestones", params: { page: 1, limit: 100, sort_by: "due_date", sort_order: "asc", ...(params ?? {}) } }), transformResponse: (response: ApiResponse<PaginatedResult<PaymentMilestone>>) => unwrapApiResponse(response), providesTags: ["Payments"] }),
  listPaymentRecords: builder.query<PaginatedResult<PaymentRecord>, ListPaymentRecordsQuery | void>({ query: (params) => ({ url: "/admin/payments/records", params: { page: 1, limit: 100, sort_by: "payment_date", sort_order: "desc", ...(params ?? {}) } }), transformResponse: (response: ApiResponse<PaginatedResult<PaymentRecord>>) => unwrapApiResponse(response), providesTags: ["Payments"] }),
  createPaymentMilestone: builder.mutation<PaymentMilestone, { projectId: string; body: PaymentMilestoneInput }>({ query: ({ projectId, body }) => ({ url: `/admin/client-projects/${projectId}/payment-milestones`, method: "POST", body }), transformResponse: (response: ApiResponse<PaymentMilestone>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  updatePaymentMilestone: builder.mutation<PaymentMilestone, { id: string; body: PaymentMilestoneInput }>({ query: ({ id, body }) => ({ url: `/admin/payment-milestones/${id}`, method: "PATCH", body }), transformResponse: (response: ApiResponse<PaymentMilestone>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  waivePaymentMilestone: builder.mutation<PaymentMilestone, string>({ query: (id) => ({ url: `/admin/payment-milestones/${id}/waive`, method: "POST" }), transformResponse: (response: ApiResponse<PaymentMilestone>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  deletePaymentMilestone: builder.mutation<Record<string, unknown>, string>({ query: (id) => ({ url: `/admin/payment-milestones/${id}`, method: "DELETE" }), transformResponse: (response: ApiResponse<Record<string, unknown>>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  createPaymentRecord: builder.mutation<Record<string, unknown>, { projectId: string; body: PaymentRecordInput }>({ query: ({ projectId, body }) => ({ url: `/admin/client-projects/${projectId}/payment-records`, method: "POST", body }), transformResponse: (response: ApiResponse<Record<string, unknown>>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  updatePaymentRecord: builder.mutation<PaymentRecord, { id: string; body: PaymentRecordInput }>({ query: ({ id, body }) => ({ url: `/admin/payment-records/${id}`, method: "PATCH", body }), transformResponse: (response: ApiResponse<PaymentRecord>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  deletePaymentRecord: builder.mutation<{ id: string; deleted: boolean }, string>({ query: (id) => ({ url: `/admin/payment-records/${id}`, method: "DELETE" }), transformResponse: (response: ApiResponse<{ id: string; deleted: boolean }>) => unwrapApiResponse(response), invalidatesTags: ["Payments", "ClientProjects"] }),
  createAdminCheckoutSession: builder.mutation<{ checkout_url?: string; session?: Record<string, unknown> }, string>({ query: (id) => ({ url: `/admin/payment-milestones/${id}/create-checkout-session`, method: "POST", body: {} }), transformResponse: (response: ApiResponse<{ checkout_url?: string; session?: Record<string, unknown> }>) => unwrapApiResponse(response), invalidatesTags: ["Payments"] }),
}) });

export const { useGetPaymentsSummaryQuery, useListPaymentMilestonesQuery, useListPaymentRecordsQuery, useCreatePaymentMilestoneMutation, useUpdatePaymentMilestoneMutation, useWaivePaymentMilestoneMutation, useDeletePaymentMilestoneMutation, useCreatePaymentRecordMutation, useUpdatePaymentRecordMutation, useDeletePaymentRecordMutation, useCreateAdminCheckoutSessionMutation } = paymentsApi;
