"use client";

import { useMemo, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Link as MuiLink, MenuItem, Paper, Skeleton, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Tooltip, Typography, useTheme } from "@mui/material";
import { alpha } from "@mui/material/styles";
import AddIcon from "@mui/icons-material/Add";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import DescriptionOutlinedIcon from "@mui/icons-material/DescriptionOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import LaunchIcon from "@mui/icons-material/Launch";
import { useAdminNotifications } from "@/components/admin/notifications/AdminNotifications";
import { useListClientProjectsQuery } from "@/lib/api/client-projects-api";
import { documentTypes, documentVisibilities, type DocumentType, type DocumentVisibility, type ProjectDocument, type ProjectDocumentInput, useCreateAdminDocumentMutation, useDeleteAdminDocumentMutation, useListAdminDocumentsQuery, useUpdateAdminDocumentMutation } from "@/lib/api/workflows-api";

type FormState = { projectId: string; title: string; description: string; documentType: DocumentType; fileUrl: string; visibility: DocumentVisibility };
const emptyForm: FormState = { projectId: "", title: "", description: "", documentType: "Project File", fileUrl: "", visibility: "Client Visible" };

function apiError(error: unknown, fallback: string) { if (error && typeof error === "object" && "data" in error) { const message = (error as { data?: { message?: string | string[] } }).data?.message; if (typeof message === "string") return message; if (Array.isArray(message)) return message.join(", "); } return fallback; }
function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : "Not set"; }

export default function DocumentsManager() {
  const theme = useTheme(); const { enqueueNotification } = useAdminNotifications();
  const [visibility, setVisibility] = useState("All"); const [projectFilter, setProjectFilter] = useState("");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<ProjectDocument | null>(null); const [form, setForm] = useState<FormState>(emptyForm);
  const documentsQuery = useListAdminDocumentsQuery({ limit: 100, visibility: visibility === "All" ? undefined : visibility, client_project_id: projectFilter || undefined });
  const projectsQuery = useListClientProjectsQuery({ limit: 100, sort_by: "created_at", sort_order: "desc" });
  const [createDocument, createState] = useCreateAdminDocumentMutation(); const [updateDocument, updateState] = useUpdateAdminDocumentMutation(); const [deleteDocument, deleteState] = useDeleteAdminDocumentMutation();
  const projects = projectsQuery.data?.data ?? []; const rows = documentsQuery.data?.data ?? [];
  const projectMap = useMemo(() => new Map(projects.map((project) => [project.id, project.title || "Untitled project"])), [projects]);
  const saving = createState.isLoading || updateState.isLoading;
  const startCreate = () => { setEditing(null); setForm({ ...emptyForm, projectId: projectFilter }); setOpen(true); };
  const startEdit = (document: ProjectDocument) => { setEditing(document); setForm({ projectId: document.client_project_id ?? "", title: document.title ?? "", description: document.description ?? "", documentType: (document.document_type as DocumentType) ?? "Project File", fileUrl: document.file_url ?? "", visibility: (document.visibility as DocumentVisibility) ?? "Client Visible" }); setOpen(true); };
  const save = async () => { if (!form.projectId || !form.title.trim() || !form.fileUrl.trim()) return; const body: ProjectDocumentInput = { title: form.title.trim(), description: form.description.trim() || undefined, document_type: form.documentType, file_url: form.fileUrl.trim(), visibility: form.visibility }; try { if (editing) await updateDocument({ id: editing.id, body }).unwrap(); else await createDocument({ projectId: form.projectId, body }).unwrap(); setOpen(false); enqueueNotification(editing ? "Document updated." : "Document added.", { variant: "success" }); } catch (error) { enqueueNotification(apiError(error, "Could not save the document."), { variant: "error" }); } };
  const remove = async (id: string) => { if (!window.confirm("Delete this document record?")) return; try { await deleteDocument(id).unwrap(); enqueueNotification("Document deleted.", { variant: "success" }); } catch (error) { enqueueNotification(apiError(error, "Could not delete the document."), { variant: "error" }); } };

  return <Stack spacing={3}>
    <Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { md: "center" } }}><Box><Typography component="h1" sx={{ fontFamily: '"Montserrat", sans-serif', fontSize: { xs: "1.9rem", md: "2.25rem" }, fontWeight: 900 }}>Documents</Typography><Typography sx={{ color: "text.secondary", mt: 0.6 }}>Manage project files, contracts, receipts, and client-visible handoff documents.</Typography></Box><Button variant="contained" startIcon={<AddIcon />} onClick={startCreate}>Add Document</Button></Stack>
    <Paper elevation={0} sx={{ overflow: "hidden", border: `1px solid ${alpha(theme.palette.common.white, 0.14)}`, bgcolor: alpha(theme.palette.background.paper, 0.78) }}>
      <Stack direction={{ xs: "column", lg: "row" }} sx={{ justifyContent: "space-between", alignItems: { lg: "center" }, borderBottom: `1px solid ${alpha(theme.palette.common.white, 0.1)}` }}><Tabs value={visibility} onChange={(_, value: string) => setVisibility(value)} sx={{ px: 1 }}><Tab value="All" label="All" /><Tab value="Client Visible" label="Client Visible" /><Tab value="Admin Only" label="Admin Only" /></Tabs><TextField select label="Project" size="small" value={projectFilter} onChange={(event) => setProjectFilter(event.target.value)} sx={{ m: 1.2, minWidth: { lg: 260 } }}><MenuItem value="">All projects</MenuItem>{projects.map((project) => <MenuItem key={project.id} value={project.id}>{project.title}</MenuItem>)}</TextField></Stack>
      {documentsQuery.isError ? <Alert severity="error" sx={{ m: 2 }}>Unable to load project documents.</Alert> : documentsQuery.isLoading ? <Stack spacing={1} sx={{ p: 2 }}>{[0,1,2,3].map((item) => <Skeleton key={item} height={58} />)}</Stack> : rows.length ? <TableContainer><Table sx={{ minWidth: 860 }}><TableHead><TableRow><TableCell>Document</TableCell><TableCell>Project</TableCell><TableCell>Type</TableCell><TableCell>Visibility</TableCell><TableCell>Added</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map((document) => <TableRow key={document.id} hover><TableCell><Typography sx={{ fontWeight: 850 }}>{document.title || "Untitled document"}</Typography><Typography noWrap sx={{ color: "text.secondary", fontSize: "0.74rem", maxWidth: 320 }}>{document.description || document.file_url}</Typography></TableCell><TableCell>{projectMap.get(document.client_project_id ?? "") || "Project"}</TableCell><TableCell>{document.document_type || "Other"}</TableCell><TableCell><Chip size="small" variant="outlined" color={document.visibility === "Client Visible" ? "primary" : "default"} label={document.visibility || "Admin Only"} /></TableCell><TableCell>{formatDate(document.created_at)}</TableCell><TableCell align="right"><Stack direction="row" spacing={0.25} sx={{ justifyContent: "flex-end" }}>{document.file_url && <Tooltip title="Open document"><IconButton component={MuiLink} href={document.file_url} target="_blank" rel="noreferrer" size="small"><LaunchIcon fontSize="small" /></IconButton></Tooltip>}<Tooltip title="Edit"><IconButton size="small" onClick={() => startEdit(document)}><EditOutlinedIcon fontSize="small" /></IconButton></Tooltip><Tooltip title="Delete"><span><IconButton size="small" color="error" disabled={deleteState.isLoading} onClick={() => void remove(document.id)}><DeleteOutlineIcon fontSize="small" /></IconButton></span></Tooltip></Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer> : <Stack spacing={1} sx={{ p: 6, alignItems: "center", textAlign: "center" }}><DescriptionOutlinedIcon sx={{ color: "primary.main", fontSize: 40 }} /><Typography sx={{ fontWeight: 900 }}>No project documents</Typography><Typography sx={{ color: "text.secondary" }}>Add contracts, project files, and handoff documents when they are ready.</Typography></Stack>}
    </Paper>
    <Dialog open={open} onClose={() => !saving && setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{editing ? "Edit Document" : "Add Document"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField select label="Project" value={form.projectId} onChange={(event) => setForm({ ...form, projectId: event.target.value })} disabled={Boolean(editing)} required fullWidth>{projects.map((project) => <MenuItem key={project.id} value={project.id}>{project.title}</MenuItem>)}</TextField><TextField label="Title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} inputProps={{ maxLength: 240 }} required fullWidth /><TextField label="Description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} multiline minRows={3} inputProps={{ maxLength: 5000 }} fullWidth /><TextField select label="Document type" value={form.documentType} onChange={(event) => setForm({ ...form, documentType: event.target.value as DocumentType })} fullWidth>{documentTypes.map((type) => <MenuItem key={type} value={type}>{type}</MenuItem>)}</TextField><TextField label="Document URL" value={form.fileUrl} onChange={(event) => setForm({ ...form, fileUrl: event.target.value })} helperText="Use a durable HTTPS URL. Private file-asset uploads require API-level document association." required fullWidth /><TextField select label="Visibility" value={form.visibility} onChange={(event) => setForm({ ...form, visibility: event.target.value as DocumentVisibility })} fullWidth>{documentVisibilities.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField></Stack></DialogContent><DialogActions><Button color="inherit" onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" disabled={saving || !form.projectId || !form.title.trim() || !form.fileUrl.trim()} onClick={() => void save()}>{saving ? "Saving..." : "Save Document"}</Button></DialogActions></Dialog>
  </Stack>;
}
